//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BH.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ECARDBEntities : DbContext
    {
        public ECARDBEntities()
            : base("name=ECARDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cartpaypal> cartpaypal { get; set; }
        public virtual DbSet<categories> categories { get; set; }
        public virtual DbSet<cuisine> cuisine { get; set; }
        public virtual DbSet<items> items { get; set; }
        public virtual DbSet<login> login { get; set; }
        public virtual DbSet<managelogin> managelogin { get; set; }
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<OrderDetails> OrderDetails { get; set; }
        public virtual DbSet<paypal> paypal { get; set; }
    }
}
